baseURL = "https://humanitarian-user-group.github.io"
languageCode = "en-us"
title = "HumanitaRian useR Group"
theme = "hugo-future-imperfect"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true
preserveTaxonomyNames = true
paginate = 10
pluralizeListTitles = false

# Disqus Username
disqusShortname = "https-humanitarian-user-group-github-io"

# Google Analytics UA number
googleAnalytics = "UA-131350181-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  identifier = "fa fa-home"
  weight = 1
  url = "/post/index.html"

[[menu.main]]
  name = "Blog"
  url = "/post/index.html"
  identifier = "fa fa-newspaper-o"
  weight = 2

[[menu.main]]
  name = "About"
  identifier = "fa fa-info-circle"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "Contributors"
  identifier = "fa fa-newspaper-o"
  url = "/tags/"
  weight = 4

[[menu.main]]
  name = "Categories"
  identifier = "fa fa-database"
  url = "/categories/"
  weight = 5

[[menu.main]]
  name = "Join the Skype-group"
  identifier = "fa fa-phone"
  url = "https://join.skype.com/qYBKC5q3wKp4"
  weight = 6

[[menu.main]]
  name = "learn more with R-bloggers"
  identifier = "fa fa-universal-access"
  url = "https://www.r-bloggers.com/"
  weight = 7

# Add your own params here
[params]
  description = "The humanitarian data analysis professional community shall work towards using a common and open language to build interoperable and transparent analysis standards for joint needs assessments and to obtain maximum value for any data collected."
  author = "HumanitaRian-useR-group"
  # Sets navbarTitle to match the section of the website
  navbarTitle          = ""
  dynamicTitles = true
  bg = "images/grey-prism.svg"
  avatar = "images/avatar.png"
  favicon = "images/favicon.ico"
  favicon16 = "images/favicon-16x16.png"
  favicon32 = "images/favicon-32x32.png"
  iconWindows = "images/tile-image-windows.png"
  iconApple = "images/touch-icon-apple.png"
  iconAndroid = "images/touch-icon-android.png"
  seotitle = "HumanitaRian-useR-group"
  subtitle = "~ Science is show me - not trust me ~"

  # Sets Estimated Reading Time to appear in post headers
  includeReadingTime = true

  # Sets where "View More Posts" links
  viewMorePostLink = "/post/"

  # Load custom CSS or JavaScript files. The variable is an array so that you
  # can load multiple files if necessary. You can also load the standard theme
  # files by adding the value, "default".
  # customCSS            = ["default", "/path/to/file"]
  # customJS             = ["default", "/path/to/file"]
  customCSS            = ["default"]
  customJS = ["default"]

  # How to cite blog article
  disable_citation = true

  ## Add highlight
  disable_highlight = false
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"


  # Choose your social networks
  email = "humanitarian.user@gmail.com"
  github = "HumanitaRian-useR-group"
  twitter = "HumanitaRianus1"
  linkedin = "https://www.linkedin.com/groups/8732707/"

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
[params.intro]
  header    = ""
  about = "The humanitarian data analysis professional community shall work towards using a common and open language to build interoperable and transparent analysis standards for joint needs assessments and to obtain maximum value for any data collected."
  paragraph = "~ Science is 'show me' - not 'trust me' ~"

  # This appears at the top of the sidebar above params.intro.header.
  # A width of less than 100px is recommended from a design perspective.
[params.intro.pic]
  src       = "images/avatar.png"
  # Sets Image to be a cirlce
  circle    = false
  # Sets Image to be Future Imperfect's hexagon
  imperfect = true
  width     = ""
  alt       = "HumanitaRian useR Group"

[params.postAmount]
# Sets the number of recent posts to show in the sidebar. The default value is 5.
  sidebar = 7
